### ISSUE TITLE
doesnt flip when there is a dot in style value

### ISSUE THREAD

**Issue by lewie6** [behrang/grunt-flipcss#4]
amazing stuff by the way

just thought id highlight a bug...

this *"padding: 0 2em 0 3em"* will flip to this *"padding: 0 3em 0 2em"* perfectly fine.

However...
this *"padding: 0 2.5em 0 3.5em"* will not flip

seems that adding a "." to the padding value stops it from working

**Comment by behrang** [comment]
Added a test for this and it is working as expected. You may have omitted the final semi-colon. Be sure that there is a semi-colon at the end. 

I close this for now.

**Comment by lewie6** [comment]
doesn't work for me..

```
body {
  padding: 0 2.5em 0 3.5em;
}
```

compiles to 

```
body {
  padding: 0 2.5em 0 3.5em;
}
```

this is my grunt task:

```
    flipcss: {
      app: {
        options: {
          warnings: true,
          flipPseudo: false,
          flipUrls: false,
          flipSelectors: false
        },
        files: {
          '/styles/default-rtl.css': '/styles/default-ltr.css'
        }
      }
    }
```

**Comment by lewie6** [comment]
did some digging...

looks like this...
npm install grunt-flipcss --save-dev

installs version 0.1.2

if i manually add the 0.3.0 files, it all works

guess there is something wrong with versioning. 

if i run *npm view grunt-flipcss versions* i get.. 
```
[
  0.1.0, 
  0.1.1,  
  0.1.2
]
```

**Comment by behrang** [comment]
Oh, I had forgotten to publish to npm. Thanks. It should now be published.
