### ISSUE TITLE
inline flags are ignored

### ISSUE THREAD

**Issue by lewie6** [behrang/grunt-flipcss#6]
hey, seems like the inline flags are ignored, eg this:

```
body{
  left: 10px; /* !direction-ignore */
}
```

compiles to:

```
body{
  right: 10px; /* !direction-ignore */
}
```

**Comment by lewie6** [comment]
did some digging...

looks like this...
npm install grunt-flipcss --save-dev

installs version 0.1.2

if i manually add the 0.3.0 files, it all works

guess there is something wrong with versioning. 

if i run *npm view grunt-flipcss versions* i get.. 
```
[
  0.1.0, 
  0.1.1,  
  0.1.2
]
```

**Comment by behrang** [comment]
As I said on #4, I had forgotten to publish it to npm. It should now be fixed.
